### ISSUE TITLE
Is there a backward IFDS analysis example?

### ISSUE THREAD

**Issue by yuffon** [secure-software-engineering/phasar#657] opened 2023-08-14 12:03 UTC
I am writing a backward IFDS analysis.
Currently, I meet some compilation error.
It is complicated to paste all the information needed here to explain this error.
But I guess it is due to some issues on the construction of backward ICFG or CFG.
Is there some example of backward IFDS analysis example that I can refer to?
Thanks.

**Comment by yuffon** [comment] 2023-08-16 06:47
> Hi @yuffon, currently we don't have an example regarding backward analysis. Can you give me some details on the error?

The compiler gives the following error:


In file included from /home/yuffon/data/programs/phasar-v2023.8.1-install-debug/include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h:22:
/home/yuffon/data/programs/phasar-v2023.8.1-install-debug/include/phasar/ControlFlow/ICFGBase.h:73:56: error: no member named 'getCallGraphImpl' in 'psr::LLVMBasedBackwardCFG'
                          std::decay_t<decltype(self().getCallGraphImpl())>>);

In my backward IFDS analysis, I use the following set:

using i_t = LLVMBasedBackwardICFG;//interprocedure control flow
using c_t = LLVMBasedBackwardCFG;//intro procedural contro flow

I don't know why the function getCallGraphImpl is resolved to class psr::LLVMBasedBackwardCFG.

**Comment by yuffon** [comment] 2023-08-16 06:57
> Hi @yuffon, currently we don't have an example regarding backward analysis. Can you give me some details on the error?

I used to succeed to implement a backward IFDS analysis using an older version of phasar.
In that project, I use the following code to construct a backward ICFG using a forward ICFG:

    psr::LLVMBasedICFG I(&DB, psr::CallGraphAnalysisType::OTF, {"main"}, &H, nullptr);
    psr::LLVMBasedBackwardICFG BI(&I);*/

But now the code cannot be complied anymore. I don't know why.
Now I am using the latest version,

**Comment by fabianbs96** [comment] 2023-08-18 15:16
Hi @yuffon, I have reproduced your issue. Can you check whether #660 fixes it?

**Comment by yuffon** [comment] 2023-08-24 09:47
Hi @fabianbs96, I find that another lib integrated in my project only supports llvm 13 or older currently.
By the way, what is the best version of phasar for llvm 12?
I have resolved some minor compiler errors based on the latesed version of phasar to make it work with llvm 12. 
But I also meet other issues posted in [#646](https://github.com/secure-software-engineering/phasar/issues/646).

If 
    1. [#646](https://github.com/secure-software-engineering/phasar/issues/646) is not caused by the LLVM version, 
    2. your patch for backward analysis is also compatible with llvm 12, 
 I will check your patch on llvm12.

**Comment by yuffon** [comment] 2023-08-29 08:00
Hi @fabianbs96 , I have test the backward analysis in my project. 
I met some compilation errors.

1. Some of them are:

```
/home/yuffon/data/programs/phasar-v2023.8.1-f-fixBackwardICFG-install-debug/include/phasar/ControlFlow/ICFGBase.h:65:44: error: no member named 'allNonCallStartNodesImpl' in 'psr::LLVMBasedBackwardCFG'
        is_iterable_over_v<decltype(self().allNonCallStartNodesImpl()), n_t>);
```

```
/home/yuffon/data/programs/phasar-v2023.8.1-f-fixBackwardICFG-install-debug/include/phasar/ControlFlow/ICFGBase.h:90:44: error: no member named 'getCallsFromWithinImpl' in 'psr::LLVMBasedBackwardCFG'
        is_iterable_over_v<decltype(self().getCallsFromWithinImpl(Fun)), n_t>);
```

```
/home/yuffon/data/programs/phasar-v2023.8.1-f-fixBackwardICFG-install-debug/include/phasar/ControlFlow/ICFGBase.h:100:44: error: no member named 'getReturnSitesOfCallAtImpl' in 'psr::LLVMBasedBackwardCFG'
        is_iterable_over_v<decltype(self().getReturnSitesOfCallAtImpl(Inst)),
```

I see that these functions have been implemented in LLVMBasedBackwardICFG. But my compiler reports that these functions are not implemented in *LLVMBasedBackwardCFG* (not ICFG).
Why?

I notice that 
```
class LLVMBasedICFG : public LLVMBasedCFG, public ICFGBase<LLVMBasedICFG>
```
and
```
class LLVMBasedBackwardICFG : public LLVMBasedBackwardCFG, public ICFGBase<LLVMBasedBackwardCFG>
```

ICFGBase has the following definitions:
```
template <typename Derived> class ICFGBase
```
and 
```
const Derived &self() const noexcept {
    return static_cast<const Derived &>(*this);
  }
```


See the class name in template. Should LLVMBasedBackwardCFG be changed to LLVMBasedBackwardICFG?

I think that is why the compiler reports LLVMBasedBackwardCFG does not implement those function, although the current version of LLVMBasedBackwardICFG has implemented them.


2. Another one error is:

```
/home/yuffon/data/programs/phasar-v2023.8.1-f-fixBackwardICFG-install-debug/include/phasar/ControlFlow/ICFGBase.h:73:56: error: no member named 'getCallGraphImpl' in 'psr::LLVMBasedBackwardCFG'
                          std::decay_t<decltype(self().getCallGraphImpl())>>);
```
`getCallGraphImpl` is not implemented in LLVMBasedBackwardICFG.

**Comment by fabianbs96** [comment] 2023-08-29 16:21
Hi @yuffon, the LLVMBasedBackwardCFG/LLVMBasedBackwardICFG confusion and the missing `getCallGraph` implementation should be fixed already in #660. Regarding the printing, how did you declare the `operator<<`? for `printSomehow` to find the `operator<<`, it should print into `llvm::raw_ostream&` (in case you use `std::ostream&`). Alternatively, you can overload the `DToString` function to handle your type specially.

**Comment by yuffon** [comment] 2023-09-03 03:30
> 

Hi @fabianbs96, I am testing backward analysis. Up to now, things seem OK to me.
I have small quesiton. In forward analysis, when dumping results, facts associated with each instruction is the data flow facts hold *before* the instruction.
But in backward analysis, it seems that in the dumped results facts associated with each isntruction is the facts hold *after* the instruction.
Is that right?

**Comment by fabianbs96** [comment] 2023-09-04 15:47
Hi @yuffon, you are right. This is, because how phasar works: The solver always propagates data flows from a current statement to the successor statements. During this propagation, it applies the flow functions to make the effects of the current statement visible at its successors. For the backwards analysis, the control-flow direction is reversed, so the successors of the current statement are actually its predecessors.

**Comment by yuffon** [comment] 2023-09-16 11:07
> Hi @yuffon, you are right. This is, because how phasar works: The solver always propagates data flows from a current statement to the successor statements. During this propagation, it applies the flow functions to make the effects of the current statement visible at its successors. For the backwards analysis, the control-flow direction is reversed, so the successors of the current statement are actually its predecessors.

Hi @fabianbs96, thanks.
I am using backward analysis in my project. I find that the above setting brings some tricky things when using analysis results.

Take the following piece for example:
```
blockA:
     inst1
     inst2
    //program point 1

blockB:
     //program point 2
     inst3
    //program point 3
    inst4
```
I want to get data flow facts before ```inst3``` (program point 2), which is different from program point 1 because blockB may be the target of some branch statement.
After backward analysis, I can only get the facts after ```inst3```. 
In my project, ```inst3``` may change data flow facts. 
So I can't exchange program point 2 and 3.

I want to know can I get data flow facts at program point 2 after backward analysis?

**Comment by fabianbs96** [comment] 2023-09-17 11:05
Hi @yuffon, we are facing a similar problem as well. For forward analyses, we use the `resultsAtInLLVMSSA` API as a workaround, but it also does not work for all cases.

Currently, we are discussing about how to fix this problem properly, e.g. introducing dummy statements within the ICFG, or adapting the solver. We will keep you updated.

**Comment by fabianbs96** [comment] 2023-09-24 11:35
Hi @yuffon, can you check whether #669 solves your problem when using the `PropagateOntoStrategy`?

**Comment by yuffon** [comment] 2023-10-11 08:57
> Hi @yuffon, can you check whether #669 solves your problem when using the `PropagateOntoStrategy`?

Just back from vacation. I have tested 'PropagateOntoStrategy' on one simple problem. It contains branches whose two successors have different facts. It works. 
Great! I can switch freely between forward/backward and PropagateOver/PropagateOnto now. That is exactly what I need.
Thanks.

**Closed** 2023-10-27 11:46 UTC
