### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by legendtang** [secure-software-engineering/phasar#198] opened 2020-09-17 16:42 UTC
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description
Run the bc with any call graph analysis then it crashes

```
phasar-llvm --call-graph-analysis=CHA -m omnetpp_s_base.mytest-m64.bc
```

```
PhASAR v0320
A LLVM-based static analysis framework

Segmentation fault
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Run the analysis properly

### Context (Environment)

Phasar commit ID: 82733ae
OS: CentOS 7
LLLVM version: 10.0.1

**Operating System:**
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

**Build Type:** 
  - [x] cmake
  - [ ] custom build

### Possible solution
n/a

### Example files

**Files:**
[omnetpp_s_base.mytest-m64.bc.zip](https://github.com/secure-software-engineering/phasar/files/5240674/omnetpp_s_base.mytest-m64.bc.zip)
[povray_r_base.mytest-m64.bc.zip](https://github.com/secure-software-engineering/phasar/files/5240758/povray_r_base.mytest-m64.bc.zip)

**Comment by pdschubert** [comment] 2020-10-20 14:52
Hi,

Thanks for reporting the bug. We have been able to spot the cause of the bug and are currently working on a fix. We will push the fix to `development` and `master` as soon as possible.

Cheers,
Philipp

**Comment by MMory** [comment] 2020-10-20 21:38
Hi @legendtang , could you please provide all of the c++ source needed to compile omnetpp_s_base.mytest-m64.bc? That would make debugging easier for us. Thank you!

Cheers
Martin

**Comment by pdschubert** [comment] 2020-10-21 07:12
@legendtang We fixed one bug. However, we now triggered another bug and it currently looks like there is something wrong with the bitcode. A vtable of a type is accessed at index 38 but it only comprises 38 function entries--resulting in an off-by-one error. This may be the result of undefined behavior in the source code. To get to the bottom of that, it would be really nice if you could provide us with the complete source code as Martin already suggested.

**Comment by legendtang** [comment] 2020-10-21 07:26
@MMory I have sent the source code to @pdschubert via email since the source code is a commercial one. Let me know if you have problems generate the corresponding bitcode file.

**Comment by MMory** [comment] 2020-10-21 08:54
Thanks for sending the source file.
There is a mismatch between the attached bitcode file and the source you just sent us.

The issue we're having currently is in NEDTypeInfo::mergePropertyKey. When we llvm-dis the bc file you sent us we see the following signature:

@_ZNK11NEDTypeInfo16mergePropertyKeyEP18PropertyKeyElementPKS0_(%class.NEDTypeInfo* %this, %class.PackageElement* %basekey, %class.PackageElement* %key)

which is a contradiction. Demangling the name yields the proper signature, but the arguments are of wrong type.

When we compile nedtypeinfo.cc the proper IR (with proper arguments) is generated and the code differs from the bitcode you sent us. We are unable to build the whole program though as the Makefile needs some deps which you didn't send along. It would be helpful if we were able to perform a whole program build.

Which version of clang did you use to compile your program to bc?

**Comment by pdschubert** [comment] 2020-10-21 09:01
So in essence we fixed a real bug in Phasar but then encountered a second one that is caused by the original bitcode file you send us. The bitcode file that you provided is not valid/correct and thus causes Phasar's virtual function resolution to crash. However, as Martin explained in detail, we have been able to compile the correct IR from the compilation unit that contains the said function.

**Comment by legendtang** [comment] 2020-10-21 09:18
> Thanks for sending the source file.
> There is a mismatch between the attached bitcode file and the source you just sent us.
> 
> The issue we're having currently is in NEDTypeInfo::mergePropertyKey. When we llvm-dis the bc file you sent us we see the following signature:
> 
> @_ZNK11NEDTypeInfo16mergePropertyKeyEP18PropertyKeyElementPKS0_(%class.NEDTypeInfo* %this, %class.PackageElement* %basekey, %class.PackageElement* %key)
> 
> which is a contradiction. Demangling the name yields the proper signature, but the arguments are of wrong type.
> 
> When we compile nedtypeinfo.cc the proper IR (with proper arguments) is generated and the code differs from the bitcode you sent us. We cannot build the whole program though as the Makefile needs some deps that you didn't send along. It would be helpful if we were able to perform a whole program build.
> 
> Which version of clang did you use to compile your program to bc?

I make no changes to the source, and I download the clang v10.0.1 [source code](https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/clang-10.0.1.src.tar.xz) and compile it.

The Makefile does not seem to work since the whole compilation is done through SPEC CPU utilities. Sorry for providing the full sources. However, I disagree that the IR is not proper since everything is untouched vanilla. I suppose the signature mismatch is caused by some special compiling commands brought by the building scripts. Nevertheless, I will send you the complete source instead.

**Comment by MMory** [comment] 2020-10-21 09:21
Could you please extract the ll file from the bc file you sent us? Just to exclude the possibility that llvm-dis did something wrong on my machine.

**Comment by legendtang** [comment] 2020-10-21 09:29
> Could you please extract the ll file from the bc file you sent us? Just to exclude the possibility that llvm-dis did something wrong on my machine.

[omnetpp_s_base.mytest-m64.ll.zip](https://github.com/secure-software-engineering/phasar/files/5414794/omnetpp_s_base.mytest-m64.ll.zip)

**Comment by MMory** [comment] 2020-10-21 09:45
Okay, your ll file also has the weird signature. Is there a way you could determine the compile command that compiles nedtypeinfo.cc?

**Comment by legendtang** [comment] 2020-10-21 10:44
> Okay, your ll file also has the weird signature. Is there a way you could determine the compile command that compiles nedtypeinfo.cc?

I have sent the full source and its instruction to @pdschubert since I don't have your email address. Please take a look at the email and reproduce the build.

**Comment by pdschubert** [comment] 2020-10-21 11:17
Thanks. I've forwarded your email to Martin. We'll try to figure out where it goes wrong. There must be some step in between that leads to the strangely modified IR.

As said, the IR that Martin and I produced by compiling the individual compilation unit differs from yours. We'll let you know once we gain new insights.

**Comment by MMory** [comment] 2020-10-22 08:48
A brief update: as @pdschubert wrote in a related issue (https://github.com/secure-software-engineering/phasar/issues/200#issuecomment-714312700), llvm-link merges "identical" data types, e.g. those which have identical fields. When that happens, phasar fails to identify the correct vtable for that type and in your case, luckily, it leads to a crash. We will fix that.

**Comment by qtcdxxyuc** [comment] 2021-02-26 07:38
> phasar/lib/PhasarLLVM/ControlFlow/Resolver/Resolver.cpp | line 78

```c++
const llvm::Function *
Resolver::getNonPureVirtualVFTEntry(const llvm::StructType *T, unsigned Idx,
                                    llvm::ImmutableCallSite CS) {
  if (TH->hasVFTable(T)) {
    const auto *Target = TH->getVFTable(T)->getFunction(Idx);
    if (Target && Target->hasName() && Target->getName() != "__cxa_pure_virtual") {
      return Target;
    }
  }
  return nullptr;
}
```

I am using llvm@10. some times Target == nullptr.

 `.bc`file create with `gllvm`，it is using `llvm-link`.

so i  check it in line 6. 

It seems that no error.
[db_bench.bc.zip](https://github.com/secure-software-engineering/phasar/files/6048111/db_bench.bc.zip)

**Comment by MMory** [comment] 2022-12-01 13:06
Is this still an issue  @legendtang

**Closed** 2023-10-27 11:52 UTC
