### ISSUE TITLE
Assertion error: `Idx < Formals.size() && "Out of bound access to formal parameters!"' failed.

### ISSUE THREAD

**Issue by boehmseb** [secure-software-engineering/phasar#200] opened 2020-09-23 11:25 UTC
- [x] I have searched open and closed issues for duplicates
  - [x] I made sure that I am not using an old project version (DO: pull Phasar, update git submodules, rebuild the project and check if the bug is still there)

----------------------------------------

### Bug description

I have a small example c++ project that I try to analyze with VaRA. 
The analysis crashes with an assertion error: _Assertion `Idx < Formals.size() && "Out of bound access to formal parameters!"' failed._

### Steps to reproduce
  - I am using Phasar with [VaRA](se-passau/VaRA) using the [VaRA-Tool-Suite](se-passau/VaRA-Tool-Suite)
  - I am using Phasar commit d11d816
  - the easiest way to reproduce the issue is to use the VaRA-Tool-Suite
    - you need to use se-passau/VaRA-Tool-Suite@91404bc (branch f-Scenarios)
    - extract the [paper config](https://github.com/secure-software-engineering/phasar/files/5267214/paper_config.zip) to the Tool-Suite's root folder
    - extract [BlameAnalyzisScenarios.zip](https://github.com/secure-software-engineering/phasar/files/5267138/BlameAnalyzisScenarios.zip) into your `benchbuild/tmp` folder
    - run `benchbuild run -E GenerateBlameReport ba_scenarios`; this should generate a file in your Tool-Suite's result folder containing the error log (similar to [this](https://github.com/secure-software-engineering/phasar/files/5267167/BR-ba_scenarios-all-8cf77b38db_30d58570-0b29-4dd6-8ad9-3d393b2da671_failed.txt))

**Actual result:** The analysis crashes ([error log](https://github.com/secure-software-engineering/phasar/files/5267167/BR-ba_scenarios-all-8cf77b38db_30d58570-0b29-4dd6-8ad9-3d393b2da671_failed.txt))

**Expected result:** The analysis completes without error

### Example files

**Files:**

Triggering example: [BlameAnalyzisScenarios.zip](https://github.com/secure-software-engineering/phasar/files/5267138/BlameAnalyzisScenarios.zip)
VaRA-TS paper config: [paper_config.zip](https://github.com/secure-software-engineering/phasar/files/5267214/paper_config.zip)
Error log: [BR-ba_scenarios-all-8cf77b38db_30d58570-0b29-4dd6-8ad9-3d393b2da671_failed.txt](https://github.com/secure-software-engineering/phasar/files/5267167/BR-ba_scenarios-all-8cf77b38db_30d58570-0b29-4dd6-8ad9-3d393b2da671_failed.txt)

**Comment by pdschubert** [comment] 2020-10-21 09:12
Hi Sebastian,

Thanks for reporting the bug. One quick question: are there any C++ programs among the programs that trigger the assertion.

**Comment by boehmseb** [comment] 2020-10-21 09:17
Hi, 
yes, this happens with a C++ program. I linked it in the report as _Triggering example_. Unfortunately, it is not quite a MWE.

**Comment by pdschubert** [comment] 2020-10-21 09:39
Okay, that's good news. @MMory and I worked on an issue that is concerned with the resolution of virtual function calls. We are pretty confident that the corresponding fix will also solve this very issue here.

I'm not sure if I'll find the time to test the fix using your experiment today myself. If you find some time to day you are welcome to re-run the experiments using Phasar's `f-fixVTableRetrieval` branch which contains the fix. Please let us know if that also fixes this issue.

**Comment by boehmseb** [comment] 2020-10-21 11:07
I ran the experiment with this branch and now, even more seems to be broken.
Here is an updated version of my demo project: [calculator.zip](https://github.com/secure-software-engineering/phasar/files/5415331/calculator.zip)

Before, revision d890d96ac2 of this project could be analyzed, but with the branch you mentioned, this revision is also broken. This updated project still is no MWE, but at least you now have a diff  where the bug triggering change is introduced.

Here is the stacktrace revision d890d96ac2 of my test project: 
[BR-ba_scenarios-all-d890d96ac2_98cd66dc-4b82-49b8-beb2-02c944403e5f_failed.txt](https://github.com/secure-software-engineering/phasar/files/5415386/BR-ba_scenarios-all-d890d96ac2_98cd66dc-4b82-49b8-beb2-02c944403e5f_failed.txt)

Also, I discovered that the other two revisions of the test project now produce a different stacktrace (on phasar-master and f-fixVTableRetrieval). I'm not quite sure what I have changed to cause that behavior.
Here is the new stacktrace for revision 205a58de80 of my test project: 
[BR-ba_scenarios-all-205a58de80_e599a056-cf62-45ac-8b17-51dc20223a33_failed.txt](https://github.com/secure-software-engineering/phasar/files/5415407/BR-ba_scenarios-all-205a58de80_e599a056-cf62-45ac-8b17-51dc20223a33_failed.txt)

**Comment by pdschubert** [comment] 2020-10-22 08:06
I just had a discussion with @MMory and we all of a sudden fell into a deep rabbit hole.

We just recognized that the linker (llvm-link) collapses types that are structurally identical. This is problematic as even types that define virtual functions are collapsed. The problem is that if you only analyze the concrete virtual call site the receiver type (and its vtable) may not matches the vtable index. So if we only have plain LLVM IR we, in addition, need to analyze all potential constructor calls on the receive object of the virtual call site under analysis. To do that, however, you already need pointer, call-graph and type hierarchy information :vomiting_face: or to put it in other words: it's really complicated.

However, there is a shortcut: if debugging information (`-g`) are available there is in easy way out of this hell. Luckily, debug infos are preserved across linking. @MMory and I will implement a fix on Friday afternoon. We'll ping you once its done. We are pretty sure, that the issue I just mentioned is responsible for the mismatches that occur while mapping parameters in the analysis.

**Comment by MMory** [comment] 2022-05-06 14:28
Is the issue fixed or not? I'm kinda confused with the history.

**Comment by boehmseb** [comment] 2022-05-06 14:30
I think so, but maybe let @vulder confirm this.

**Comment by vulder** [comment] 2022-05-07 12:37
At least from what we currently see, the initial issue seems fixed. However, I cannot guarantee that it works for all vtable scenarios, as we don't have very good test coverage on that.
I'm closing this issue for now, should we find more examples in the future we can always revisit it.

**Closed by vulder** 2022-05-07 12:37 UTC
